name: Greetings

on: [pull_request_target, issues, push]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Thank you for highlighting this issue, other users will benefit from your contribution!"
        pr-message: "Thank you for submitting this pull request, other users will benefit from your contribution!"
